services:
    configsvr:
        image: mongo:8.0.12
        container_name: configsvr
        command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017
        ports:
            - 10001:27017
        volumes:
            - configdata:/data/db
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M

    mongodb1:
        image: mongo:8.0.12
        container_name: mongodb1
        command: mongod --shardsvr --replSet shard_rs --dbpath /data/db --port 27017
        ports:
            - 20001:27017
        volumes:
            - mongodata1:/data/db
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 2048M

    mongodb2:
        image: mongo:8.0.12
        container_name: mongodb2
        command: mongod --shardsvr --replSet shard_rs --dbpath /data/db --port 27017
        ports:
            - 20002:27017
        volumes:
            - mongodata2:/data/db
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 2048M

    mongodb3:
        image: mongo:8.0.12
        container_name: mongodb3
        command: mongod --shardsvr --replSet shard_rs --dbpath /data/db --port 27017
        ports:
            - 20003:27017
        volumes:
            - mongodata3:/data/db
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 2048M

    mongos:
        image: mongo:8.0.12
        container_name: mongos
        command: mongos --configdb config_rs/192.168.178.56:10001 --bind_ip 0.0.0.0 --port 27017
        ports:
            - 30001:27017
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M


volumes:
    configdata:
    mongodata1:
    mongodata2:
    mongodata3:
